name: Build
run-name: Build - ${{ github.ref }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  IAC_PATH: '.examples'
  IAC_DEPTH: 2

jobs:
  build_iac:
    name: Build (IaC)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and test projects
        uses: amilochau/github-actions/build/terraform@v4
        with:
          modulesPath: ${{ env.IAC_PATH }}
          modulesPathDepth: ${{ env.IAC_DEPTH }}